# Generated by Django 3.2.12 on 2024-04-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='analysis',
            field=models.TextField(default='ANALYISIS'),
        ),
        migrations.AddField(
            model_name='full',
            name='analysis',
            field=models.TextField(default='ANALYISIS'),
        ),
        migrations.AddField(
            model_name='microbio',
            name='analysis',
            field=models.TextField(default='ANALYISIS'),
        ),
    ]
