# Generated by Django 3.2.12 on 2024-06-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chemical',
            name='analysis',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='recommendation',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='full',
            name='analysis',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='full',
            name='recommendation',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='microbio',
            name='analysis',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='microbio',
            name='recommendation',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='parameters',
            field=models.ManyToManyField(related_name='industries', to='core.Parameter'),
        ),
    ]
