# Generated by Django 3.2.12 on 2024-04-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240407_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='sample',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.sample'),
        ),
    ]
