# Generated by Django 3.2.12 on 2024-07-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240622_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='max_limits',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='test_method',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
