# Generated by Django 3.2.12 on 2024-03-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_changelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'managed': False},
        ),
    ]
