# Generated by Django 3.2.12 on 2024-07-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240714_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='is_non_water',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parameter',
            name='is_water',
            field=models.BooleanField(default=False),
        ),
    ]
