# Generated by Django 3.2.12 on 2024-04-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240407_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='recommendation',
            field=models.TextField(default='RECOMMENDATION'),
        ),
        migrations.AddField(
            model_name='full',
            name='recommendation',
            field=models.TextField(default='RECOMMENDATION'),
        ),
        migrations.AddField(
            model_name='microbio',
            name='recommendation',
            field=models.TextField(default='RECOMMENDATION'),
        ),
    ]
